<?php /** @var $block \Amc\UserSchedule\Block\Adminhtml\Schedule\Edit\Js */ ?>
<script>
    require([
        'scheduleEvent',
        'mage/backend/notification',
        'moment',
        'jquery',
        'jquery/jquery-ui',
        'fullcalendar-scheduler/lib/fullcalendar.min',
        'fullcalendar-scheduler/scheduler'
    ], function(scheduleEvent, notification, moment, $){

        $(function() {

            $('.users-list .fc-event').each(function() {
                // store data so the calendar knows to render an event upon drop
                $(this).data('event', {
                    title: $.trim($(this).text()), // use the element's text as the event title
                    stick: true // maintain when user navigates (see docs on the renderEvent method)
                });
                // make the event draggable using jQuery UI
                $(this).draggable({
                    zIndex: 999,
                    revert: true,      // will cause the event to go back to its
                    revertDuration: 0  //  original position after the drag
                });
            });

            $('#calendar').fullCalendar({
                schedulerLicenseKey: 'GPL-My-Project-Is-Open-Source',
                now: '<?php echo $block->getCurrentDate(); ?>',
                editable: true,
                droppable: true,
                aspectRatio: 1.8,
                eventOverlap: false,
                businessHours: {
                    start: '9:00',
                    end: '20:00',
                    dow: [ 1, 2, 3, 4, 5 ]
                },
                minTime: '09:00',
                maxTime: '20:00',
                slotDuration: '00:15',
                slotWidth: 20,
                slotLabelFormat: 'HH:mm',
                header: {
                    left: 'today prev,next',
                    center: 'title',
                    right: 'timelineDetailedDay,timelineDay,timelineThreeDays'
                },
                defaultView: 'timelineDay',
                views: {
                    timelineThreeDays: {
                        type: 'timeline',
                        duration: { days: 3 }
                    }
                },
                resourceAreaWidth: '200px',
                resourceLabelText: '<?php echo $block->getResourceLabel(); ?>',
                resources: <?php echo $block->getRoomsCollectionJson(); ?>,
                events: <?php echo $block->getEventsCollectionJson(); ?>,
                drop: function() {
                    scheduleEvent.registry.pushRegistry('userId', $(this).data('userId'));
                },
                eventReceive: function(event) {
                    event.userId = scheduleEvent.registry.popRegistry('userId');
                    $('#calendar').fullCalendar('updateEvent', event);

                    scheduleEvent.registry.registerEvent(event);
                },
                eventResize: function(event) {
                    scheduleEvent.registry.registerEvent(event);
                },
                eventDrop: function(event) {
                    scheduleEvent.registry.registerEvent(event);
                }
            });

            $('.save-schedule').on('click', function(event) {

                event.preventDefault();

                var events = [];

                $.each(scheduleEvent.registry.getEvents(), function(index, item) {
                    events.push({
                        entity_id: item.id,
                        user_id: item.userId,
                        room_id: item.resourceId,
                        all_day: item.allDay,
                        start_at: item.start,
                        end_at: item.end
                    });
                });

                if (events.length) {
                    jQuery('body').trigger('processStart');
                    $.post("<?php echo $block->getSaveActionUrl(); ?>", {data: JSON.stringify(events)})
                        .done(function( data ) {
                            scheduleEvent.registry.reset();
                            jQuery('body').trigger('processStop');
                        })
                        .fail(function() {
                            jQuery('body').trigger('processStop');
                            $('body').notification('clear').notification('add', {
                                error: true,
                                message: $.mage.__('Error happened during schedule save.'),
                                insertMethod: function(message) {
                                    $('.page-main-actions').after(message);
                                }
                            });
                        });
                }
            });

        });
    });
</script>
