<?php /** @var $block \Amc\Timetable\Block\Adminhtml\Order\TimetableInterface */ ?>
<!--
<div class="admin__page-section-title">
    <strong class="title"><?php echo __('Order Timetable') ?></strong>
</div>
-->
<div id="timetable-fullcalendar" data-mage-init='{"Amc_Timetable/js/timetable": <?php echo $block->getWidgetOptionsJson() ?>}'></div>

<div class="timetable-save">
    <button id="timetable-save" title="Save" type="button" class="action-default scalable save primary" onclick="">
        <span>Save</span>
    </button>
</div>
