<?php
namespace Amc\Protocol\Block\Adminhtml;

use Magento\Framework\Data\Form\Element\Select;

class Renderer extends Select
{
    public function getAfterElementHtml()
    {
        return '<a href="qwe" data-selector="dmitro" >open dialog</a>';
    }

    public function getAfterElementJs()
    {
        return parent::getAfterElementJs(); // TODO: Change the autogenerated stub
    }


}
