<?php
namespace Amc\Protocol\Block\Adminhtml;

use Magento\Framework\Data\Form\Element\AbstractElement;
use Magento\Framework\Data\Form\Element\CollectionFactory;
use Magento\Framework\Data\Form\Element\Factory;
use Magento\Framework\Data\Form\Element\Select;
use Magento\Framework\Escaper;
use Magento\TestFramework\Event\Magento;

class Renderer extends Select
{
    protected $protocolFactory;

    /**
     * @param Factory $factoryElement
     * @param CollectionFactory $factoryCollection
     * @param Escaper $escaper
     * @param \Amc\Protocol\Model\ProtocolFactory $protocolFactory
     * @param array $data
     */
    public function __construct(
        Factory $factoryElement,
        CollectionFactory $factoryCollection,
        Escaper $escaper,
        \Amc\Protocol\Model\ProtocolFactory $protocolFactory,
        $data = []
    )
    {
        $this->protocolFactory = $protocolFactory;
        parent::__construct($factoryElement, $factoryCollection, $escaper, $data);
    }

    public function getAfterElementHtml()
    {
        return '<a href="/admin/protocol/index/load" data-selector="dmitro" >open dialog</a>';
    }

    public function getAfterElementJs()
    {
        return parent::getAfterElementJs(); // TODO: Change the autogenerated stub
    }

    public function getValues()
    {
        return $this->protocolFactory->create()->getResourceCollection()->toOptionArray();
    }


}
