<?php
// @codingStandardsIgnoreFile
/** @var \Magento\Sales\Block\Adminhtml\Order\Create\Data $block */
?>
<div class="page-create-order">
    <script>
    require(["Magento_Sales/order/create/form"], function(){
        order.setCurrencySymbol('<?php /* @escapeNotVerified */ echo $block->getCurrencySymbol($block->getCurrentCurrencyCode()) ?>')
    });
</script>
    <div class="order-details<?php if ($block->getCustomerId()): ?> order-details-existing-customer<?php endif; ?>">

        <div id="order-additional_area" style="display: none" class="admin__page-section order-additional-area">
            <?php echo $block->getChildHtml('additional_area') ?>
        </div>

        <section id="order-timetable" class="admin__page-section order-timetable">
            <?php echo $block->getChildHtml('timetable') ?>
        </section>

        <div id="order-search" style="display: none" class="admin__page-section order-search-items">
            <?php echo $block->getChildHtml('search') ?>
        </div>

        <section id="order-items" class="admin__page-section order-items" data-mage-init='{"loader": {}}'>
            <?php echo $block->getChildHtml('items') ?>
        </section>

        <div id="order-errors" class="order-errors"><?php echo $block->getChildHtml('errors') ?></div>

        <section id="order-methods" class="admin__page-section order-methods">
            <div class="admin__page-section-title">
                <span class="title"><?php /* @escapeNotVerified */ echo __('Payment Information') ?></span>
            </div>
            <div class="admin__page-section-content">
                <div id="order-billing_method" class="admin__page-section-item order-billing-method">
                    <?php echo $block->getChildHtml('billing_method') ?>
                </div>
                <div class="order-discounts">
                    <div id="order-coupons" class="order-coupons"><?php echo $block->getChildHtml('coupons') ?></div>
                </div>

                <div id="order-shipping_method" class="admin__page-section-item order-shipping-method" style="display: none;">
                    <?php echo $block->getChildHtml('shipping_method') ?>
                </div>
            </div>
        </section>

        <?php if ($block->getChildBlock('card_validation')): ?>
        <section id="order-card_validation" class="admin__page-section order-card-validation">
            <?php echo $block->getChildHtml('card_validation') ?>
        </section>
        <?php endif; ?>

        <?php echo $block->getChildHtml('gift_options') ?>

        <section class="admin__page-section order-summary">
            <div class="admin__page-section-title">
                <span class="title"><?php /* @escapeNotVerified */ echo __('Order Total') ?></span>
            </div>
            <div class="admin__page-section-content">
                <fieldset class="admin__fieldset order-history" id="order-comment">
                    <legend class="admin__legend"><span><?php /* @escapeNotVerified */ echo __('Order History') ?></span></legend>
                    <br>
                    <?php echo $block->getChildHtml('comment') ?>
                </fieldset>
                <fieldset id="order-totals" class="admin__fieldset order-totals">
                    <?php echo $block->getChildHtml('totals') ?>
                </fieldset>
            </div>
        </section>
    </div>

    <div class="order-sidebar">

        <div class="admin__field field-comment">

            <section id="order-addresses" >
                <!-- address container also contains account fields in order to manage fields order -->
                <div id="order-billing_address">
                    <?php echo $block->getChildHtml('billing_address') ?>
                </div>
                <div id="order-shipping_address" style="display: none;">
                </div>
            </section>

            <!-- keep container for safe, account fields moved to address container -->
            <section id="order-form_account" style="display: none;">
            </section>
        </div>

        <?php if ($block->getCustomerId()): ?>

            <div class="store-switcher order-currency" style="display: none;">
                <label class="admin__field-label" for="currency_switcher">
                    <?php /* @escapeNotVerified */ echo __('Order Currency:') ?>
                </label>
                <select id="currency_switcher"
                        class="admin__control-select"
                        name="order[currency]"
                        onchange="order.setCurrencyId(this.value); order.setCurrencySymbol(this.options[this.selectedIndex].getAttribute('symbol'));">
                    <?php foreach ($block->getAvailableCurrencies() as $_code): ?>
                        <option value="<?php /* @escapeNotVerified */ echo $_code ?>"<?php if ($_code == $block->getCurrentCurrencyCode()): ?> selected="selected"<?php endif; ?> symbol="<?php /* @escapeNotVerified */ echo $block->getCurrencySymbol($_code) ?>">
                            <?php /* @escapeNotVerified */ echo $block->getCurrencyName($_code) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="customer-current-activity" id="order-sidebar" style="margin-top: 40px;">
                <?php echo $block->getChildHtml('sidebar') ?>
            </div>
        <?php endif; ?>
    </div>

</div>
