<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                buttons: [{
                    text: $.mage.__('Continue'),
                    click: function () {
                        this.closeModal();
                        order.productGridAddSelected();
                    }
                }]
            };

            // hide default actions since we cannot control buttons there
            $("#order-items .actions").hide();
            // insert our custom actions
            $("div.actions-amc").insertAfter("#order-items .actions");
            $("#order-items .actions-amc").show();

            var popup = modal(options, $('#order-search'));
            // show popup only
            if ($('#order-items').is(':visible')) {
                popup.openModal();
            }
            $('#order-items .actions-amc').on('click', 'button.action-add', function (){
                popup.openModal();
            });
        }
    );
</script>
