<div class="page-actions">
    <div class="page-actions-inner">
        <div class="page-actions-buttons">
            <button id="add"
                    title="<?php echo __('Create New Order') ?>"
                    type="button"
                    class="scalable primary"
                    onclick="location.href = '<?php echo $block->getUrl('sales/order_create/start') ?>';"
                    >
                <span><?php echo __('Create New Order') ?></span>
            </button>
        </div>
    </div>
</div>
