<?php /** @var $block \Amc\Timetable\Block\Adminhtml\Schedule */ ?>
<div id="index-timetable"></div>

<script>
    require([
        "moment",
        "jquery",
        "jquery/jquery-ui",
        "fullcalendar",
        "fullcalendarScheduler"
    ], function(moment, $){

        $(function() { // document ready
//            $( "#datepicker" ).datepicker($.calendarConfig);
            var $timetable = $('#index-timetable');
            window.index_timetable = $timetable;

            $timetable.fullCalendar({
                defaultDate: '<?php echo $block->getInitialDate() ?>',
                editable: false,
                contentHeight: 'auto',
                scrollTime: '00:00',
                header: {
                    left: 'today prev,next',
                    center: 'title',
                    right: 'timelineDay,timelineThreeDays'
                },
                defaultView: 'timelineDay',
                views: {
                    timelineThreeDays: {
                        type: 'timeline',
                        duration: { days: 3 }
                    }
                },
                businessHours: {
                    start: '8:00',
                    end: '19:00',
                    dow: [ 1, 2, 3, 4, 5 ]
                },
                minTime: '08:00', // todo: impldement config "Working hours"
                maxTime: '19:00', // todo: impldement config "Working hours"
                slotLabelFormat: 'HH:mm',
                eventOverlap: true, // will cause the event to take up entire resource height
                resourceAreaWidth: '25%',
                resourceLabelText: "<?php echo $block->escapeQuote(__('Executant')) ?>",
                selectable: false,
                selectHelper: true,
                slotDuration: '00:15',
                slotWidth: 15,
                eventClick: function(event, jsEvent, view) {
                    location.href = "<?php echo $block->getUrl('timetable/index/gotoevent') ?>item/" + event.order_item_id;
                },

                resources: function(callback) {
                    $.getJSON(
                        '<?php echo $block->getUrl('timetable/index/resourcesJson') ?>',
                        {date: $timetable.fullCalendar('getDate').format()},
                        function (data) {
                            callback(data);
                        }
                    );
                },

                events: {
                    url: '<?php echo $block->getUrl('timetable/index/eventsJson') ?>',
                    type: 'GET'
                },

                resourceRender: function(resource, labelTds) {
                    $(labelTds).find('.fc-cell-text').html(resource.title + '<sup>' + resource.position + '</sup>');
                },

                viewRender: function () {
                    console.log('viewRender');
                    $timetable.fullCalendar('refetchResources');
                }
            });
        });
    });
</script>
