<?php /** @var $block \Amc\Timetable\Block\Adminhtml\Order\Tab\Timetable */ ?>
<div class="admin__page-section-title">
    <strong class="title"><?php echo __('Order Timetable') ?></strong>
</div>
<div id="timetable-fullcalendar"></div>
<script type="text/x-magento-init">
{
    "#timetable-fullcalendar": {
        "Amc_Timetable/js/timetable": <?php echo $block->getWidgetOptionsJson() ?>
    }
}
</script>
