<?php /** @var $block \Amc\Timetable\Block\Adminhtml\Order\Tab\Timetable */ ?>
<div class="admin__page-section-title">
    <strong class="title"><?php echo __('Order Timetable') ?></strong>
</div>
<div id="order-timetable"></div>
<input type="hidden" name="order[timetable_json]" id="timetable_json" value=""/>
<script type="text/x-magento-init">
{
    "#order-timetable": {
        "Amc_Timetable/js/timetable": <?php echo $block->getWidgetOptionsJson() ?>
    }
}
</script>
