<?php
namespace Amc\Consultation\Model\ResourceModel\Order\Collection;

use Magento\Framework\Data\Collection\Db\FetchStrategyInterface as FetchStrategy;
use Magento\Framework\Data\Collection\EntityFactoryInterface as EntityFactory;
use Magento\Framework\Event\ManagerInterface as EventManager;
use Psr\Log\LoggerInterface as Logger;
use Amc\Consultation\Model\ResourceModel\Select as SelectHelper;

class Grid extends \Magento\Framework\View\Element\UiComponent\DataProvider\SearchResult
{
    /** @var \Amc\Consultation\Model\ResourceModel\Select */
    private $selectHelper;

    public function __construct(
        EntityFactory $entityFactory,
        Logger $logger,
        FetchStrategy $fetchStrategy,
        EventManager $eventManager,
        $mainTable,
        $resourceModel,
        SelectHelper $selectHelper
    ) {
        $this->selectHelper = $selectHelper;
        parent::__construct($entityFactory, $logger, $fetchStrategy, $eventManager, $mainTable, $resourceModel); // TODO: Change the autogenerated stub
    }

    protected function _initSelect()
    {
        parent::_initSelect();
        $this->selectHelper->joinProductName($this->getSelect());
        $this->selectHelper->joinUserName($this->getSelect());
        return $this;
    }
}
