<script>
    require([
        "moment",
        "jquery",
        "jquery/jquery-ui",
        "fullcalendar-scheduler-1.0.2/lib/fullcalendar.min",
        "fullcalendar-scheduler-1.0.2/scheduler"
    ], function(moment, $){

        $(function() {

            $('#external-events .fc-event').each(function() {
                // store data so the calendar knows to render an event upon drop
                $(this).data('event', {
                    title: $.trim($(this).text()), // use the element's text as the event title
                    stick: true // maintain when user navigates (see docs on the renderEvent method)
                });
                // make the event draggable using jQuery UI
                $(this).draggable({
                    zIndex: 999,
                    revert: true,      // will cause the event to go back to its
                    revertDuration: 0  //  original position after the drag
                });
            });

            $('#calendar').fullCalendar({
                schedulerLicenseKey: 'GPL-My-Project-Is-Open-Source',
                now: '<?php echo date('Y-m-d') ?>',
                editable: true, // enable draggable events
                droppable: true, // this allows things to be dropped onto the calendar
                aspectRatio: 2.0,
                scrollTime: '00:00', // undo default 6am scrollTime
                header: {
                    left: 'today prev,next',
                    center: 'title',
                    right: 'timelineDay,timelineThreeDays,agendaWeek,month'
                },
                defaultView: 'timelineDay',
                views: {
                    timelineThreeDays: {
                        type: 'timeline',
                        duration: { days: 3 }
                    }
                },
                resourceLabelText: 'Rooms',
                resources: [
                    { id: 'a', title: 'Room A' },
                    { id: 'b', title: 'Room B', eventColor: 'green' },
                    { id: 'c', title: 'Room C', eventColor: 'orange' },
                    { id: 'd', title: 'Room D', children: [
                        { id: 'd1', title: 'Room D1' },
                        { id: 'd2', title: 'Room D2' }
                    ] },
                    { id: 'e', title: 'Room E' },
                    { id: 'f', title: 'Room F', eventColor: 'red' },
                    { id: 'g', title: 'Room G' }
                ],
                events: [
                    { id: '1', resourceId: 'b', start: '2015-11-07T02:00:00', end: '2015-11-07T07:00:00', title: 'event 1' },
                    { id: '2', resourceId: 'c', start: '2015-11-07T05:00:00', end: '2015-11-07T22:00:00', title: 'event 2' },
                    { id: '3', resourceId: 'd', start: '2015-11-06', end: '2015-11-08', title: 'event 3' },
                    { id: '4', resourceId: 'e', start: '2015-11-07T03:00:00', end: '2015-11-07T08:00:00', title: 'event 4' },
                    { id: '5', resourceId: 'f', start: '2015-11-07T00:30:00', end: '2015-11-07T02:30:00', title: 'event 5' }
                ],
                drop: function() {
                    // is the "remove after drop" checkbox checked?
                    if ($('#drop-remove').is(':checked')) {
                        // if so, remove the element from the "Draggable Events" list
                        $(this).remove();
                    }
                },
                eventReceive: function(event) { // called when a proper external event is dropped
                    console.log('eventReceive', event);
                },
                eventDrop: function(event) { // called when an event (already on the calendar) is moved
                    console.log('eventDrop', event);
                }
            });
        });
    });
</script>
