<?php /** @var \Magento\Sales\Block\Adminhtml\Order\View\Items\Renderer\DefaultRenderer $block */ ?>
<?php $_item = $block->getItem() ?>
<?php $block->setPriceDataObject($_item) ?>
<tr>
    <?php $i = 0;
    $columns = $block->getColumns();
    $lastItemNumber = count($columns) ?>
    <?php foreach ($columns as $columnName => $columnClass):?>
        <?php $i++; ?>
        <td class="dmitro111 <?php echo /* @noEscape */ $columnClass?><?php /* @noEscape */ echo ($i === $lastItemNumber ? ' last' : '')?>">
            <?php /* @escapeNotVerified */ echo $block->getColumnHtml($_item, $columnName) ?>
            <?php if ($columnName === 'product'): ?>
                <div id="timetable-state-<?php /* @escapeNotVerified */ echo $_item->getId() ?>" class="timetable-state"></div>
            <?php endif ?>
        </td>
    <?php endforeach; ?>
</tr>
